# -*- coding: utf-8 -*-
"""BlockHouse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_s7yFs7S32HUm0w33Y0ChVnAUmmcFyRQ
"""

"""
Cont–Kukanov back‑test (with progress log & plots)
• --fine adds local refinement but stays < 2 min.
• Exact allocator (100‑share grid) + 60 % fill haircut.
• Saves results_bar.png (annotated bar) and results.png (cumulative cost).
"""
from __future__ import annotations
import json, math, sys, time, warnings
from dataclasses import dataclass
from itertools import product
from pathlib import Path
from typing import List, Tuple
import numpy as np, pandas as pd

# ───────── Config ─────────────────────────────────────────────────────────
ORDER_SIZE   = 5_000          # parent order
STEP         = 100            # allocator granularity
FILL_RATIO   = 0.60           # realised fraction of displayed size
COARSE_SET   = np.arange(0.00, 0.26, 0.05)    # 0, 0.05 … 0.25 $/sh
FINE_STEP    = 0.005          # 0.5 ¢
WINDOW_FINE  = 0.025          # ±2.5 ¢
FEES         = {2: 0.0029}    # taker fee
REBATES      = {2: 0.0020}    # maker rebate
CSV_DEFAULT  = Path("l1_day.csv")

# ───────── Data structure ────────────────────────────────────────────────
@dataclass(frozen=True)
class VenueSnap:
    venue: int
    ask: float
    ask_size: int
    @property
    def fee(self):    return FEES.get(self.venue, 0.0)
    @property
    def rebate(self): return REBATES.get(self.venue, 0.0)

# ───────── Snapshot loader ───────────────────────────────────────────────
def load_snapshots(csv: Path) -> List[List[VenueSnap]]:
    cols = ["ts_event", "publisher_id", "ask_px_00", "ask_sz_00"]
    df = pd.read_csv(csv, usecols=cols).sort_values("ts_event")
    df = df.drop_duplicates(["ts_event", "publisher_id"])
    snaps: List[List[VenueSnap]] = []
    for _, grp in df.groupby("ts_event"):
        vs = [VenueSnap(int(r.publisher_id), float(r.ask_px_00), int(r.ask_sz_00))
              for r in grp.itertuples() if r.ask_sz_00 > 0]
        vs.sort(key=lambda v: v.ask)
        snaps.append(vs)
    return snaps

# ───────── Allocator (static Cont‑Kukanov) ───────────────────────────────
def allocate(order: int, venues: List[VenueSnap],
             lam_o: float, lam_u: float, theta: float) -> List[int]:
    partial = [[]]
    for v in venues:
        nxt = []
        for alloc in partial:
            used = sum(alloc)
            for q in range(0, min(order - used, v.ask_size) + 1, STEP):
                nxt.append(alloc + [q])
        partial = nxt
    best_cost, best_alloc = math.inf, []
    for alloc in partial:
        if sum(alloc) != order:
            continue
        c = _cost(alloc, venues, order, lam_o, lam_u, theta)
        if c < best_cost:
            best_cost, best_alloc = c, alloc
    return best_alloc

def _cost(split, venues, order, lo, lu, th):
    executed = cash = 0.0
    for q, v in zip(split, venues):
        fill = min(q, v.ask_size)
        executed += fill
        cash += fill * (v.ask + v.fee)
        cash -= max(q - fill, 0) * v.rebate
    under = max(order - executed, 0)
    over  = max(executed - order, 0)
    return cash + th * (under + over) + lu * under + lo * over

# ───────── Simulation & baselines ────────────────────────────────────────
def simulate(snaps, lo, lu, th, track=False) -> Tuple[float, List[float] | None]:
    rem, cash, last = ORDER_SIZE, 0.0, 0.0
    cum = []
    for vs_raw in snaps:
        if track: cum.append(cash)
        last = vs_raw[0].ask
        vs = [VenueSnap(v.venue, v.ask, int(v.ask_size * FILL_RATIO)) for v in vs_raw]
        if rem == 0: continue
        alloc = allocate(min(rem, ORDER_SIZE), vs, lo, lu, th)
        for q, v in zip(alloc, vs_raw):
            take = min(q, int(v.ask_size * FILL_RATIO), rem)
            cash += take * (v.ask + v.fee)
            rem  -= take
            if rem == 0: break
    if track: cum.append(cash)
    if rem:
        cash += rem * (last + vs_raw[0].fee)
        if track: cum[-1] = cash
    return cash, cum if track else None

def best_ask(snaps, track=False):
    rem, cash = ORDER_SIZE, 0.0
    cum = []
    for vs in snaps:
        if track: cum.append(cash)
        v = vs[0]
        take = min(int(v.ask_size * FILL_RATIO), rem)
        cash += take * (v.ask + v.fee)
        rem  -= take
        if rem == 0: break
    if track: cum.append(cash)
    if rem:
        cash += rem * (vs[0].ask + vs[0].fee)
        if track: cum[-1] = cash
    return cash, cum if track else None

def twap(snaps, bucket=60):
    buckets = max(1, len(snaps)//bucket)
    per = math.ceil(ORDER_SIZE / buckets)
    rem, cash = ORDER_SIZE, 0.0
    for i, vs in enumerate(snaps):
        if i % bucket: continue
        need = min(per, rem)
        vs_sorted = sorted([VenueSnap(v.venue, v.ask, int(v.ask_size*FILL_RATIO))
                            for v in vs], key=lambda x: x.ask)
        for v in vs_sorted:
            take = min(v.ask_size, need)
            cash += take * (v.ask + v.fee)
            need -= take; rem -= take
            if rem == 0 or need == 0: break
        if rem == 0: break
    if rem: cash += rem * (vs[0].ask + vs[0].fee)
    return cash

def vwap(snaps):
    px_sz = sz = 0.0
    for vs in snaps:
        for v in vs:
            s = v.ask_size * FILL_RATIO
            px_sz += v.ask * s; sz += s
    px = px_sz / sz
    return px * ORDER_SIZE + FEES.get(2, 0.0) * ORDER_SIZE

# ───────── Parameter tuning (logs progress) ───────────────────────────────
def tune(snaps, fine=False):
    best_cash, best_par = math.inf, (0,0,0)
    for lo, lu, th in product(COARSE_SET, COARSE_SET, np.linspace(0,0.06,4)):
        c, _ = simulate(snaps, lo, lu, th)
        if c < best_cash:
            best_cash, best_par = c, (lo, lu, th)
            print(f"[coarse] {best_cash:,.2f}  lo={lo:.3f} lu={lu:.3f} th={th:.3f}")
    if not fine: return best_par, best_cash
    lo0, lu0, th0 = best_par
    fine_grid = product(np.arange(max(lo0-WINDOW_FINE,0), lo0+WINDOW_FINE, FINE_STEP),
                        np.arange(max(lu0-WINDOW_FINE,0), lu0+WINDOW_FINE, FINE_STEP),
                        np.arange(max(th0-WINDOW_FINE,0), th0+WINDOW_FINE, FINE_STEP))
    for lo, lu, th in fine_grid:
        c, _ = simulate(snaps, lo, lu, th)
        if c < best_cash:
            best_cash, best_par = c, (lo, lu, th)
            print(f"[ fine ] {best_cash:,.2f}  lo={lo:.3f} lu={lu:.3f} th={th:.3f}")
    return best_par, best_cash

# ───────── Main ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    warnings.filterwarnings("ignore", category=FutureWarning)
    import argparse, matplotlib.pyplot as plt, matplotlib.ticker as mtick

    parser = argparse.ArgumentParser(description="Cont‑Kukanov back‑test")
    parser.add_argument("--csv", type=Path, default=CSV_DEFAULT)
    parser.add_argument("--fine", action="store_true", help="enable local fine search")
    args, _ = parser.parse_known_args()   # ignore Jupyter’s -f arg

    snaps = load_snapshots(args.csv)

    t0 = time.time()
    (lo, lu, th), tuned_cash = tune(snaps, args.fine)
    runtime = round(time.time() - t0, 2)

    ba_cash, ba_cum = best_ask(snaps, track=True)
    tw_cash = twap(snaps)
    vw_cash = vwap(snaps)
    tuned_cash, tuned_cum = simulate(snaps, lo, lu, th, track=True)

    def bps(ref): return round(1e4*(ref-tuned_cash)/(ORDER_SIZE*(ba_cash/ORDER_SIZE)),2)

    result = {
        "best_params": {"lambda_over": lo, "lambda_under": lu, "theta_queue": th},
        "tuned_router": {"cash": tuned_cash, "avg_px": tuned_cash / ORDER_SIZE},
        "best_ask": {"cash": ba_cash, "avg_px": ba_cash / ORDER_SIZE},
        "twap": {"cash": tw_cash, "avg_px": tw_cash / ORDER_SIZE},
        "vwap": {"cash": vw_cash, "avg_px": vw_cash / ORDER_SIZE},
        "savings_bps": {"vs_best_ask": bps(ba_cash),
                        "vs_twap":     bps(tw_cash),
                        "vs_vwap":     bps(vw_cash)},
        "runtime_sec": runtime
    }
    json.dump(result, sys.stdout, indent=2); print()

    # ---- Bar chart -------------------------------------------
    try:
        import matplotlib.pyplot as plt
        labels = ["Best‑Ask", "TWAP", "VWAP", "Tuned"]
        px = [ba_cash/ORDER_SIZE, tw_cash/ORDER_SIZE, vw_cash/ORDER_SIZE, tuned_cash/ORDER_SIZE]
        bps = [0.0,
              (px[1]-px[0])/px[0]*1e4,
              (px[2]-px[0])/px[0]*1e4,
              (px[0]-px[3])/px[0]*1e4]   # positive is better

        fig, ax = plt.subplots(figsize=(6,4))
        bars = ax.bar(labels, px)

        ax.set_ylabel("Average fill price ($)")
        ax.set_title("Router vs baselines")
        ax.set_ylim(min(px)-0.1, max(px)+0.1)
        ax.yaxis.set_major_formatter(lambda x,pos: f"{x:.1f}")

        for bar, p, bp in zip(bars, px, bps):
            ax.annotate(f"${p:.4f}\n({bp:+.2f} bp)",
                        xy=(bar.get_x()+bar.get_width()/2, p),
                        xytext=(0,3), textcoords="offset points",
                        ha="center", va="bottom", fontsize=8)
        plt.tight_layout()
        plt.savefig("results_bar.png", dpi=150)
        plt.close()
    except Exception as e:
        print("[plot‑skip]", e, file=sys.stderr)

    # ---- Cumulative cost line plot -------------------------------------
    try:
        plt.figure(figsize=(6,4))
        plt.plot(ba_cum,   label="Best‑Ask")
        plt.plot(tuned_cum,label="Tuned")
        plt.xlabel("Snapshots"); plt.ylabel("Cumulative cash ($)")
        plt.title("Cumulative cost trajectory"); plt.legend()
        plt.tight_layout(); plt.savefig("results.png", dpi=150); plt.close()
    except Exception as e:
        print("[plot‑line]", e, file=sys.stderr)